# Generated by Django 4.2.25 on 2025-10-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("isActivePlayer", models.BooleanField(default=False)),
                ("cards", models.TextField()),
                ("position", models.CharField(max_length=100)),
            ],
        ),
    ]
