# Generated by Django 4.2.25 on 2025-10-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
