# Generated by Django 4.2.25 on 2025-11-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("CHAR", "Character"),
                            ("WEAP", "Weapon"),
                            ("ROOM", "Room"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Hallway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_occupied", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Lobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "lobbies",
            },
        ),
        migrations.CreateModel(
            name="StartingPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        limit_choices_to={"card_type": "CHAR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_position",
                        to="game.card",
                    ),
                ),
                (
                    "hallway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_positions",
                        to="game.hallway",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        limit_choices_to={"card_type": "CHAR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_character",
                        to="game.card",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        limit_choices_to={"card_type": "ROOM"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_room",
                        to="game.card",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        limit_choices_to={"card_type": "WEAP"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_weapon",
                        to="game.card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("has_secret_passage", models.BooleanField(default=False)),
                ("connected_rooms", models.ManyToManyField(blank=True, to="game.room")),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        help_text="The name of the character this player represents.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active_turn", models.BooleanField(default=False)),
                ("is_eliminated", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_hallway",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hallway the player currently occupies, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occupants",
                        to="game.hallway",
                    ),
                ),
                (
                    "current_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Room the player currently occupies, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occupants",
                        to="game.room",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.game",
                    ),
                ),
                (
                    "starting_position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Static starting position (character ↔ hallway).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="game.startingposition",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "character_name")},
            },
        ),
        migrations.CreateModel(
            name="LobbyPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_card",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"card_type": "CHAR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lobby_players",
                        to="game.card",
                    ),
                ),
                (
                    "lobby",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lobby_players",
                        to="game.lobby",
                    ),
                ),
            ],
            options={
                "db_table": "lobby_player",
            },
        ),
        migrations.AddField(
            model_name="hallway",
            name="room1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hallway_start",
                to="game.room",
            ),
        ),
        migrations.AddField(
            model_name="hallway",
            name="room2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hallway_end",
                to="game.room",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="current_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_turn_games",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="solution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.solution",
            ),
        ),
    ]
