# Generated by Django 4.2.25 on 2025-11-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("CHAR", "Character"),
                            ("WEAP", "Weapon"),
                            ("ROOM", "Room"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
