# Generated by Django 4.2.25 on 2025-11-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lobby",
            name="game_in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
