# Generated by Django 4.2.25 on 2025-11-06 04:05

from django.db import migrations


from django.db import migrations

def create_default_cards(apps, schema_editor):
    Card = apps.get_model('game', 'Card')

    characters = [
        "Miss Scarlet", "Professor Plum", "Mrs. Peacock",
        "Mr. Green", "Colonel Mustard", "Mrs. White"
    ]
    weapons = [
        "Candlestick", "Dagger", "Lead Pipe",
        "Revolver", "Rope", "Wrench"
    ]
    rooms = [
        "Study", "Hall", "Lounge", "Library",
        "Billiard Room", "Dining Room",
        "Conservatory", "Ballroom", "Kitchen"
    ]

    for name in characters:
        Card.objects.get_or_create(name=name, card_type="CHAR")
    for name in weapons:
        Card.objects.get_or_create(name=name, card_type="WEAP")
    for name in rooms:
        Card.objects.get_or_create(name=name, card_type="ROOM")

def delete_default_cards(apps, schema_editor):
    Card = apps.get_model('game', 'Card')
    Card.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_cards, delete_default_cards),
    ]

