# Generated by Django 4.2.25 on 2025-11-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lobbyplayer",
            name="name",
        ),
    ]
