# Generated by Django 4.2.25 on 2025-12-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_lobby_game_in_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lobby",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
