# Generated by Django 4.2.25 on 2025-11-06 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_populate_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        limit_choices_to={"card_type": "CHAR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_character",
                        to="game.card",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        limit_choices_to={"card_type": "ROOM"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_room",
                        to="game.card",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        limit_choices_to={"card_type": "WEAP"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_weapon",
                        to="game.card",
                    ),
                ),
            ],
        ),
    ]
