# Generated by Django 4.2.25 on 2025-11-06 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_solution"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("has_secret_passage", models.BooleanField(default=False)),
                ("connected_rooms", models.ManyToManyField(blank=True, to="game.room")),
            ],
        ),
        migrations.CreateModel(
            name="Hallway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "room1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hallway_start",
                        to="game.room",
                    ),
                ),
                (
                    "room2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hallway_end",
                        to="game.room",
                    ),
                ),
            ],
        ),
    ]
