# Generated by Django 4.2.25 on 2025-11-06 04:29

from django.db import migrations

def create_rooms_and_hallways(apps, schema_editor):
    Room = apps.get_model('game', 'Room')
    Hallway = apps.get_model('game', 'Hallway')

    # --- Create Rooms ---
    rooms = {
        "Study": Room.objects.get_or_create(name="Study", has_secret_passage=True)[0],
        "Hall": Room.objects.get_or_create(name="Hall")[0],
        "Lounge": Room.objects.get_or_create(name="Lounge", has_secret_passage=True)[0],
        "Library": Room.objects.get_or_create(name="Library")[0],
        "Billiard Room": Room.objects.get_or_create(name="Billiard Room")[0],
        "Dining Room": Room.objects.get_or_create(name="Dining Room")[0],
        "Conservatory": Room.objects.get_or_create(name="Conservatory", has_secret_passage=True)[0],
        "Ballroom": Room.objects.get_or_create(name="Ballroom")[0],
        "Kitchen": Room.objects.get_or_create(name="Kitchen", has_secret_passage=True)[0],
    }

    # --- Secret Passages (diagonal links) ---
    rooms["Study"].connected_rooms.add(rooms["Kitchen"])
    rooms["Kitchen"].connected_rooms.add(rooms["Study"])
    rooms["Lounge"].connected_rooms.add(rooms["Conservatory"])
    rooms["Conservatory"].connected_rooms.add(rooms["Lounge"])

    # --- Horizontal Hallways ---
    Hallway.objects.get_or_create(name="Hallway 1", room1=rooms["Study"], room2=rooms["Hall"])
    Hallway.objects.get_or_create(name="Hallway 2", room1=rooms["Hall"], room2=rooms["Lounge"])
    Hallway.objects.get_or_create(name="Hallway 3", room1=rooms["Library"], room2=rooms["Billiard Room"])
    Hallway.objects.get_or_create(name="Hallway 4", room1=rooms["Billiard Room"], room2=rooms["Dining Room"])
    Hallway.objects.get_or_create(name="Hallway 5", room1=rooms["Conservatory"], room2=rooms["Ballroom"])
    Hallway.objects.get_or_create(name="Hallway 6", room1=rooms["Ballroom"], room2=rooms["Kitchen"])

    # --- Vertical Hallways ---
    Hallway.objects.get_or_create(name="Hallway 7", room1=rooms["Study"], room2=rooms["Library"])
    Hallway.objects.get_or_create(name="Hallway 8", room1=rooms["Hall"], room2=rooms["Billiard Room"])
    Hallway.objects.get_or_create(name="Hallway 9", room1=rooms["Lounge"], room2=rooms["Dining Room"])
    Hallway.objects.get_or_create(name="Hallway 10", room1=rooms["Library"], room2=rooms["Conservatory"])
    Hallway.objects.get_or_create(name="Hallway 11", room1=rooms["Billiard Room"], room2=rooms["Ballroom"])
    Hallway.objects.get_or_create(name="Hallway 12", room1=rooms["Dining Room"], room2=rooms["Kitchen"])


def delete_rooms_and_hallways(apps, schema_editor):
    Room = apps.get_model('game', 'Room')
    Hallway = apps.get_model('game', 'Hallway')
    Hallway.objects.all().delete()
    Room.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_hallway'),  # adjust if your room/hallway migration has another number
    ]

    operations = [
        migrations.RunPython(create_rooms_and_hallways, delete_rooms_and_hallways),
    ]

