# Generated by Django 4.2.25 on 2025-11-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_populate_board"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active_turn", models.BooleanField(default=False)),
                ("is_eliminated", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_card",
                    models.OneToOneField(
                        blank=True,
                        help_text="Which character this player represents.",
                        limit_choices_to={"card_type": "CHAR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.card",
                    ),
                ),
                (
                    "current_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current room or hallway on the board.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.room",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "character_card")},
            },
        ),
        migrations.AddField(
            model_name="game",
            name="current_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_turn_games",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="solution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.solution",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="starting_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.room",
            ),
        ),
    ]
