# Generated by Django 4.2.25 on 2025-11-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_seed_starting_hallway"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="starting_room",
        ),
        migrations.AddField(
            model_name="player",
            name="current_hallway",
            field=models.ForeignKey(
                blank=True,
                help_text="Hallway the player currently occupies, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occupants",
                to="game.hallway",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="current_room",
            field=models.ForeignKey(
                blank=True,
                help_text="Room the player currently occupies, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occupants",
                to="game.room",
            ),
        ),
    ]
