# Generated by Django 4.2.25 on 2025-11-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_remove_game_starting_room_player_current_hallway_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartingPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        limit_choices_to={"card_type": "CHAR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_position",
                        to="game.card",
                    ),
                ),
                (
                    "hallway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_positions",
                        to="game.hallway",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="starting_position",
            field=models.ForeignKey(
                blank=True,
                help_text="Static starting position (character ↔ hallway).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="game.startingposition",
            ),
        ),
    ]
